
spring:
  profiles:
    active: local


# h2
---

spring:
  profiles: local
  datasource:
#    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    platform: test

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#logging:
#  level:
#    ROOT: error


#mysql
---
spring:
  profiles: dev
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
    url: jdbc:mysql://localhost:3306/booktest?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    platform: test

#logging:
#  level:
#    ROOT: error
